version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: webhooks
    restart: unless-stopped
    environment:
      POSTGRES_DB:  webhooks 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  
